// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZU3UZZFpZrYYBdtBM7MhEzsTMahLKZ6U',
    appId: '1:247135459910:web:515d560bd1dc4c3f8f0847',
    messagingSenderId: '247135459910',
    projectId: 'yomeanimo-f0bca',
    authDomain: 'yomeanimo-f0bca.firebaseapp.com',
    storageBucket: 'yomeanimo-f0bca.appspot.com',
    measurementId: 'G-XZYPK8R6V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqLACDkaC-8F113-y2HNE5AAns-NofTk',
    appId: '1:247135459910:android:09135a1a4bc13b168f0847',
    messagingSenderId: '247135459910',
    projectId: 'yomeanimo-f0bca',
    storageBucket: 'yomeanimo-f0bca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNgVQyx8lcp0bWv3wisV0Bt6Y_Pu4Q7l4',
    appId: '1:247135459910:ios:dadef33d790ac99d8f0847',
    messagingSenderId: '247135459910',
    projectId: 'yomeanimo-f0bca',
    storageBucket: 'yomeanimo-f0bca.appspot.com',
    iosBundleId: 'com.example.yoMeAnimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNgVQyx8lcp0bWv3wisV0Bt6Y_Pu4Q7l4',
    appId: '1:247135459910:ios:207ba9fca88150598f0847',
    messagingSenderId: '247135459910',
    projectId: 'yomeanimo-f0bca',
    storageBucket: 'yomeanimo-f0bca.appspot.com',
    iosBundleId: 'com.example.yoMeAnimo.RunnerTests',
  );
}
